pipeline: 
  render:
    image: ncatelli/hugo_builder:v0.29 
    pull: true
    commands:
      - /usr/local/bin/hugo
  s3:
    image: plugins/s3:1
    bucket: packetfire
    strip_prefix: public/
    source: public/**/*
    target: /
    acl: public-read
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      event: push
      branch: master
