pipeline: 
  render:
    image: ncatelli/hugo_builder:v0.29 
    pull: true
    commands:
      - /usr/local/bin/hugo

  s3-sync:
    image: plugins/s3-sync:1
    bucket: packetfire
    region: us-east-1
    source: public/
    delete: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]

  webhook:
    image: ncatelli/hugo_builder:v0.29
    commands:
      - 'curl -kH "Content-type: application/json" -H "Accept: application/json" -d "{\"urls\": [{\"url\": \"http://www.packetfire.org/*\"}]}" "$WEBHOOK_URLS" -u "$WEBHOOK_USERNAME:$WEBHOOK_PASSWORD" -s'
    secrets: [ webhook_username, webhook_password, webhook_urls ]
