pipeline: 
  render:
    image: ncatelli/hugo_builder:v0.29 
    pull: true
    commands:
      - /usr/local/bin/hugo
  s3:
    image: plugins/s3
    bucket: packetfire
    source: public/*
    target: /
    endpoint: https://nyc3.digitaloceanspaces.com
    secrets: [ access_key, secret_key ]
