pipeline: 
  render:
    image: plugins/hugo:1.1
    output: public
    validate: true
  publish:
    image: plugins/s3:1
    bucket: packetfire
    strip_prefix: public/
    acl: public
    source: public/*
    target: /
    endpoint: https://nyc3.digitaloceanspaces.com
    secrets: [ aws_access_key_id, aws_secret_access_key ]
