image: debian:9.1

build:
  stage: build
  script:
    - apt-get update -y
    - apt-get install -y hugo rsync
    - hugo
    - echo $RSYNC_PASSWORD > /tmp/rsync_password
    - rsync -arvzh --progres --pasword-file=/tm/rsync_password public $RSYNC_USER@$TARGET_SERVER::$RSYNC_PATH/
    - rm -rf /tmp/rsync_password
  only:
    - master
