language: generic
sudo: true
services:
  - docker

env:
  HUGO_IMAGE: 'hugo_builder'
  HUGO_VERSION: '0.29'

before_install:
  - pushd scripts/hugo_builder/
  - docker build -t $HUGO_IMAGE .
  - popd
  - sudo apt-get install -y curl

stages:
  - name: 'Build and Deploy'
  - name: 'Clear Cache'
    if: branch = master AND type = push

jobs:
  include:
    - stage: "Build and Deploy"
      script: docker run --rm -e HUGO_VERSION -v $PWD:/data -w /data $HUGO_IMAGE
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: packetfire
        region: us-east-1
        local_dir: public
        skip_cleanup: true
        acl: public_read
        on:
          branch: master
    - stage: "Clear Cache" 
      name: "Clear beluga cache."
      script: 'curl -kH "Content-type: application/json" -H "Accept: application/json" -d "{\"urls\": [{\"url\": \"http://www.packetfire.org/*\"}]}" "$WEBHOOK_URLS" -u "$WEBHOOK_USERNAME:$WEBHOOK_PASSWORD" -s'
      on:
        branch: master
