services:
  - docker

env:
  HUGO_BUILD_VERSION: "v0.29"

before_install:
  - docker pull ncatelli/hugo_builder:$HUGO_BUILD_VERSION

script:
  - docker run --rm -v $PWD:/work -w /work ncatelli/hugo_builder:$HUGO_BUILD_VERSION /usr/local/bin/hugo

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: packetfire
  region: us-east-1
  local_dir: public
  skip_cleanup: true
  acl: public_read
  on:
    branch: master